openapi: 3.0.3
info:
  title: TestShop
  description: Testshop-API
  version: 1.0.0

servers:
  - url: https://api.testshop.local/v1
    description: Testumgebung

paths:
  /produkte:
    get:
      summary: Liste aller Produkte abrufen
      description: Gibt eine Liste aller verfügbaren Produkte im Testshop zurück.
      responses:
        '200':
          description: Erfolgreiche Abfrage
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Produkt'

  /produkte/{id}:
    get:
      summary: Details eines Produkts abrufen
      parameters:
        - name: id
          in: path
          required: true
          description: Die eindeutige ID des Produkts
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Produkt gefunden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Produkt'
        '404':
          description: Produkt nicht gefunden

  /bestellungen:
    post:
      summary: Neue Bestellung erstellen
      description: Legt eine neue Bestellung im Testshop an.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Bestellung'
      responses:
        '201':
          description: Bestellung erfolgreich erstellt
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BestellungResponse'

  /bestellungen/{id}:
    get:
      summary: Details einer Bestellung abrufen
      parameters:
        - name: id
          in: path
          required: true
          description: Die eindeutige ID der Bestellung
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Bestellung gefunden
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Bestellung'
        '404':
          description: Bestellung nicht gefunden

components:
  schemas:
    Produkt:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 1
        name:
          type: string
          example: Testprodukt
        beschreibung:
          type: string
          example: Beschreibung des Testprodukts
        preis:
          type: number
          format: float
          example: 19.99
        verfuegbar:
          type: boolean
          example: true

    Bestellung:
      type: object
      properties:
        kundenName:
          type: string
          example: Max Mustermann
        adresse:
          type: string
          example: Musterstraße 1, 12345 Musterstadt
        produktIds:
          type: array
          items:
            type: integer
          example:
            - 1
            - 2
            - 3

    BestellungResponse:
      type: object
      properties:
        bestellId:
          type: integer
          format: int64
          example: 1001
        status:
          type: string
          example: bestätigt
